#! /usr/bin/env python3
import os
count=0
print('Choose a set character:')
setChar = input('>')
print('Choose a file:')
file = input('>')
os.system('echo \"$(cat '+file+')\" > pyread.txt')
file = open('pyread.txt', 'r')
words = file.read()
for char in words:
	if char == ' ':
		print(' ',end='')
	elif char == '\t':
		print('\t',end='')
	elif char == '\n':
		print('\n',end='')
	elif char == setChar:
		print('\033[95m'+char+'\033[00m', end='')
		count+=1
	else:
		print('\u00b7', end ='')
print('\n---------------------------------\nNumber of occurences: '+str(count))
os.system('rm pyread.txt')
