#! /bin/bash
values=(Ace Two Three Four Five Six Seven Eight Nine Ten Jack Queen King)
suits=(Spades Hearts Clubs Diamonds)

if [ "$1" == '-l' ]; then
suitz[0]="$2"
suitz[1]="$3"
suitz[2]="$4"
suitz[3]="$5"
echo "${values[$((RANDOM%13))]} of ${suitz[$((RANDOM%4))]}"
elif [ "$1" == '-s' ]; then
echo "${values[$((RANDOM%13))]} of $2"
elif [ "$1" == '-v' ]; then
echo "$2 of ${suits[$((RANDOM%4))]}"
else
echo "${values[$((RANDOM%13))]} of ${suits[$((RANDOM%4))]}"
fi
